version: '3'

# SERVICES
# #####################################################################

services:

# MOSQUITTO Frontend
  mosquittofront:
    container_name: mosquittofront
    image: eclipse-mosquitto
    ports:
        - 0.0.0.0:1883:1883
        - 0.0.0.0:9001:9001
    volumes:
      - ./mosquitto_frontend:/mosquitto
    networks:
      - net

# MOSQUITTO Backend
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto_backend:/mosquitto
    networks:
      - net

# CORE
  core:
    container_name: core
    image: 'thinkfree84/ax5_core:latest'
    depends_on:
      - mosquitto
    build:
      context: ../
      dockerfile: src/core/Dockerfile
    environment:
      - AX_BROKER=mosquitto
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - ./config:/etc/ax5
    networks:
      - net

# ADMIN
  admin:
    container_name: admin
    image: 'thinkfree84/ax5_admin:latest'
    depends_on:
      - core
    build:
      context: ../
      dockerfile: src/tasks/admin/Dockerfile
    environment:
      - AX_BROKER=mosquitto
      - AX_HOST=admin
      - AX_PORT=8123
    volumes:
      - ./config:/etc/ax5
    networks:
      - net

# PLUGINS
  plugins:
    container_name: plugins
    image: 'thinkfree84/ax5_plugins:latest'
    depends_on:
      - core
    build:
      context: ../
      dockerfile: src/tasks/plugins/Dockerfile
    environment:
      - AX_BROKER=mosquitto
      - AX_HOST=plugins
      - AX_PORT=8123
    volumes:
      - ./config:/etc/ax5
      - ./plugins/:/etc/plugins/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

# NETWORKS
# #####################################################################

networks:
  net:
    driver: bridge
